# Generated by Django 2.2.5 on 2019-09-06 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ToDoList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200, null=True, verbose_name='Описание')),
                ('status', models.TextField(default='New', max_length=3000, null=True, verbose_name='Статус')),
                ('done_at', models.DateField(auto_now_add=True, verbose_name='Дата выполнения')),
            ],
        ),
    ]
