# Generated by Django 2.2.5 on 2019-09-10 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_auto_20190906_0717'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolist',
            name='text',
            field=models.TextField(max_length=3000, null=True, verbose_name='Подробное описание'),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='description',
            field=models.CharField(max_length=200, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='done_at',
            field=models.DateField(null=True, verbose_name='Дата выполнения'),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('In progress', 'In progress'), ('done', 'Done')], default='new', max_length=3000, verbose_name='Статус'),
        ),
    ]
