# Generated by Django 2.2.5 on 2019-09-10 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_auto_20190910_0822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='description',
            field=models.CharField(default='', max_length=200, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='done_at',
            field=models.DateField(default='', null=True, verbose_name='Дата выполнения'),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='text',
            field=models.TextField(default='', max_length=3000, null=True, verbose_name='Подробное описание'),
        ),
    ]
